// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOdGqAn4lLvlEq59eOoINokEPHbS42RQQ',
    appId: '1:608998763205:web:3ae0b00196a1b9ae04deac',
    messagingSenderId: '608998763205',
    projectId: 'quentinha-app-c58a8',
    authDomain: 'quentinha-app-c58a8.firebaseapp.com',
    storageBucket: 'quentinha-app-c58a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxw9c8DJALnvYGaPJ8nbmJNqPGDja9aLo',
    appId: '1:608998763205:android:a3826db7a993c65c04deac',
    messagingSenderId: '608998763205',
    projectId: 'quentinha-app-c58a8',
    storageBucket: 'quentinha-app-c58a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcC4p61OnLs0RZgdhFbUOxWcHidlW-bng',
    appId: '1:608998763205:ios:238c1a0e7d449dd704deac',
    messagingSenderId: '608998763205',
    projectId: 'quentinha-app-c58a8',
    storageBucket: 'quentinha-app-c58a8.firebasestorage.app',
    iosClientId:
        '608998763205-bolrakag8smuqli9vbb40ke0ki794kjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quentinhaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcC4p61OnLs0RZgdhFbUOxWcHidlW-bng',
    appId: '1:608998763205:ios:238c1a0e7d449dd704deac',
    messagingSenderId: '608998763205',
    projectId: 'quentinha-app-c58a8',
    storageBucket: 'quentinha-app-c58a8.firebasestorage.app',
    iosClientId:
        '608998763205-bolrakag8smuqli9vbb40ke0ki794kjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quentinhaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOdGqAn4lLvlEq59eOoINokEPHbS42RQQ',
    appId: '1:608998763205:web:5d6706b68bb7c79f04deac',
    messagingSenderId: '608998763205',
    projectId: 'quentinha-app-c58a8',
    authDomain: 'quentinha-app-c58a8.firebaseapp.com',
    storageBucket: 'quentinha-app-c58a8.firebasestorage.app',
  );
}
